  CREATE TABLE "WKAI"."GZLIBRARYURL"
   (	"BOOKTYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE,
	"PAGENUM" NUMBER(3,0) NOT NULL ENABLE,
	"URL" VARCHAR2(300 BYTE),
	"DOWNFLAG" VARCHAR2(20 BYTE) DEFAULT 0,
	 CONSTRAINT "TABLE1_PK" PRIMARY KEY ("BOOKTYPE", "PAGENUM")
   );
   COMMENT ON COLUMN "WKAI"."GZLIBRARYURL"."BOOKTYPE" IS '书籍一级分类';
   COMMENT ON COLUMN "WKAI"."GZLIBRARYURL"."PAGENUM" IS 'pagesize=1000 ';
   COMMENT ON COLUMN "WKAI"."GZLIBRARYURL"."URL" IS '书籍分页页面';
   COMMENT ON COLUMN "WKAI"."GZLIBRARYURL"."DOWNFLAG" IS '0:未下载 1:已下载';

  CREATE TABLE "WKAI"."GZLIBBOOKINFO"
   (	"ID" VARCHAR2(20 BYTE) NOT NULL ENABLE PRIMARY KEY,
	"NAME" VARCHAR2(200 BYTE),
	"AUTHOR" VARCHAR2(200 BYTE),
	"PRESS" VARCHAR2(100 BYTE),
	"PUBDATE" VARCHAR2(30 BYTE),
	"COLUMN1" VARCHAR2(20 BYTE)
   )  ;
   COMMENT ON COLUMN "WKAI"."GZLIBBOOKINFO"."ID" IS 'id';
   COMMENT ON COLUMN "WKAI"."GZLIBBOOKINFO"."NAME" IS '书名';
   COMMENT ON COLUMN "WKAI"."GZLIBBOOKINFO"."AUTHOR" IS '作者';
   COMMENT ON COLUMN "WKAI"."GZLIBBOOKINFO"."PRESS" IS '出版社';
   COMMENT ON COLUMN "WKAI"."GZLIBBOOKINFO"."PUBDATE" IS '出版时间';
